# pubspec.yaml

name: virus_total_scanner
description: Advanced VirusTotal Scanner with clipboard monitoring and multi-platform support
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization support
  flutter_localizations:
    sdk: flutter

  # HTTP requests
  http: ^1.2.0
  
  # Local notifications
  flutter_local_notifications: ^17.0.0
  
  # Clipboard monitoring
  clipboard_watcher: ^0.2.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.20.2
  
  # URL launcher (for opening links)
  url_launcher: ^6.2.4
  
  # File picker (for import/export)
  file_picker: ^6.1.1
  
  # Path provider (for file operations)
  path_provider: ^2.1.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Enable generation of localized Strings
  generate: true
  
  # Assets
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/