# pubspec.yaml

name: virus_total_scanner
description: Advanced VirusTotal Scanner with clipboard monitoring and KDE integration
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.1.0
  
  # Local notifications
  flutter_local_notifications: ^17.0.0
  
  # Clipboard monitoring
  clipboard_watcher: ^0.2.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.19.0
  
  # State management (optional, for future use)
  provider: ^6.1.1
  
  # URL launcher (for opening links)
  url_launcher: ^6.2.4
  
  # File picker (for import/export)
  file_picker: ^6.1.1
  
  # Path provider (for file operations)
  path_provider: ^2.1.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0
  
  # Build runner (for code generation)
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts (optional)
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

# Platform specific configurations
flutter:
  # Android configuration
  android:
    min_sdk_version: 21
    target_sdk_version: 34
    compile_sdk_version: 34
    
  # Linux configuration  
  linux:
    desktop_file:
      name: "VirusTotal Scanner"
      comment: "Advanced URL scanner with real-time monitoring"
      categories: ["Security", "Network"]
      icon: "security-medium"
      
  # Windows configuration
  windows:
    app_name: "VirusTotal Scanner"
    app_description: "Advanced URL scanner"